[package]
name = "rust-rt-one-weekend"
version = "0.1.0"
authors = ["pavel <pavel.remygailo+github@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.11.2"
rand = "0.7.2"